import type { Card, Set } from './types'

export const mockSets: Set[] = [
  {
    id: 'sv151',
    name: 'Scarlet & Violet — 151',
    releaseDate: '2023-09-22',
    cardCount: 165,
    imageUrl: 'https://images.pokemontcg.io/sv3pt5/logo.png',
  },
  {
    id: 'sv4',
    name: 'Paradox Rift',
    releaseDate: '2023-11-03',
    cardCount: 182,
    imageUrl: 'https://images.pokemontcg.io/sv4/logo.png',
  },
  {
    id: 'sv3',
    name: 'Obsidian Flames',
    releaseDate: '2023-08-11',
    cardCount: 197,
    imageUrl: 'https://images.pokemontcg.io/sv3/logo.png',
  },
  {
    id: 'sv2',
    name: 'Paldea Evolved',
    releaseDate: '2023-06-09',
    cardCount: 193,
    imageUrl: 'https://images.pokemontcg.io/sv2/logo.png',
  },
]

export const mockCards: Card[] = [
  {
    id: 'sv151-006',
    name: 'Charizard ex',
    number: '006/165',
    rarity: 'Double Rare',
    imageUrl: 'https://images.pokemontcg.io/sv3pt5/6.png',
    setId: 'sv151',
    setName: 'Scarlet & Violet — 151',
  },
  {
    id: 'sv151-025',
    name: 'Pikachu',
    number: '025/165',
    rarity: 'Common',
    imageUrl: 'https://images.pokemontcg.io/sv3pt5/25.png',
    setId: 'sv151',
    setName: 'Scarlet & Violet — 151',
  },
  {
    id: 'sv151-130',
    name: 'Mew ex',
    number: '130/165',
    rarity: 'Double Rare',
    imageUrl: 'https://images.pokemontcg.io/sv3pt5/130.png',
    setId: 'sv151',
    setName: 'Scarlet & Violet — 151',
  },
  {
    id: 'sv151-173',
    name: 'Charizard ex',
    number: '173/165',
    rarity: 'Ultra Rare',
    imageUrl: 'https://images.pokemontcg.io/sv3pt5/173.png',
    setId: 'sv151',
    setName: 'Scarlet & Violet — 151',
  },
  {
    id: 'sv4-125',
    name: 'Garchomp ex',
    number: '125/182',
    rarity: 'Double Rare',
    imageUrl: 'https://images.pokemontcg.io/sv4/125.png',
    setId: 'sv4',
    setName: 'Paradox Rift',
  },
  {
    id: 'sv4-164',
    name: 'Iron Valiant ex',
    number: '164/182',
    rarity: 'Double Rare',
    imageUrl: 'https://images.pokemontcg.io/sv4/164.png',
    setId: 'sv4',
    setName: 'Paradox Rift',
  },
  {
    id: 'sv3-125',
    name: 'Charizard ex',
    number: '125/197',
    rarity: 'Double Rare',
    imageUrl: 'https://images.pokemontcg.io/sv3/125.png',
    setId: 'sv3',
    setName: 'Obsidian Flames',
  },
  {
    id: 'sv2-193',
    name: 'Iono',
    number: '193/193',
    rarity: 'Special Illustration Rare',
    imageUrl: 'https://images.pokemontcg.io/sv2/193.png',
    setId: 'sv2',
    setName: 'Paldea Evolved',
  },
]
